os:
  edit: "nvr -s -l {{filename}}"
  editAtLine: "nvr -s -l +{{line}} {{filename}}"
  editAtLineAndWait: "nvr -s -l --remote-wait +{{line}} {{filename}}"
  editPreset: "nvim"
promptToReturnFromSubprocess: false
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
keybinding:
  commits:
    moveDownCommit: "J"
    moveUpCommit: "K"
    renameCommitWithEditor: "r"
    renameCommit: "R"
gui:
  scrollHeight: 20
  nerdFontsVersion: "3"
  skipRewordInEditorWarning: true
notARepository: "quit"
