## which style to use
## possible values: auto, full, compact
style = "compact"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 40

## Invert the UI - put the search bar at the top
invert = true

## If enabled, upon hitting enter Atuin will immediately execute the command
## Press tab to return to the shell and edit
enter_accept = true

## Prevent scrolling past the end from exiting search
[keys]
scroll_exits = false

[sync]
## Enable sync v2 by default
records = true
